version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    healthcheck:
      test: alembic upgrade head
      interval: 10s
      timeout: 5s
      retries: 5
    # command: alembic upgrade head
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./.env
  #   environment:
  #     - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
  #     - DATABASE_PORT=${DATABASE_PORT}
  #     - DATABASE_NAME=${DATABASE_NAME}
  #     - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  #     - DATABASE_USERNAME=${DATABASE_USERNAME}
  #     - SECRET_KEY=${SECRET_KEY}
  #     - ALGORITHM=${ALGORITHM}
  #     - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - postgres-db:/var/lib/postgressql/data

volumes:
  postgres-db:
