"""add_phone_to_users_table

Revision ID: 450da1cda150
Revises: 3ccae0067bb6
Create Date: 2022-02-16 23:47:08.810590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450da1cda150'
down_revision = '3ccae0067bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
